name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 17, 21]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
      - run: mvn wrapper:wrapper --no-transfer-progress -Dmaven="3.9.9"
      - run: ./mvnw -B install --fail-at-end --no-transfer-progress --file pom.xml
